name: Snyk Minimal Test

on:
  workflow_call:
    inputs:
      language:
        description: 'Project language'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Language is ${{ inputs.language }}"
